/* Biblioteca de ejercicios de cali — SOLO aptos para tendinitis del supraespinoso.
 * Prohibido: press sobre la cabeza, elevaciones laterales >90°, dips, remo al mentón,
 * rotaciones con carga, movimientos tras la nuca.
 * Convenciones:
 *  - `id` estable: es la clave de las preferencias guardadas (favoritos/ocultos).
 *  - `grupo`: bloque corporal para el circuito tipo entrenador (piernas | core | torso | cardio).
 *  - `img: null → marcador emoji hasta tener SVG/foto (plan de medios híbrido).
 *  - `wger`: id en wger.de para enlazar ficha/vídeo (CC-BY-SA). */
const EJERCICIOS = [
  // ── Calentamiento / movilidad ──────────────────────────────────────────
  { id: "marcha-suave", video: "0e4251eQAE8", nombre: "Marcha en el sitio", categoria: "calentamiento", segundos: 60,
    img: "assets/img/video-marcha-suave.jpg",
    claves: ["Pasos suaves, sin saltar", "Brazos relajados a la altura de la cintura", "Respira por la nariz"] },
  { id: "circulos-hombros", video: "8xQao07OrF0", nombre: "Círculos de hombro suaves", categoria: "calentamiento", segundos: 40,
    img: "assets/img/video-circulos-hombros.jpg",
    notaHombro: "Rango corto y sin dolor; para si notas pinchazo",
    claves: ["Hombros arriba, atrás y abajo", "Círculos pequeños, 20 s por sentido"] },
  { id: "gato-camello", video: "J99uL4J5khE", nombre: "Gato–camello", categoria: "calentamiento", segundos: 40,
    img: "assets/img/gato-camello.jpg",
    claves: ["A cuatro patas, manos bajo hombros", "Arquea y redondea la espalda despacio", "Exhala al redondear"] },
  { id: "circulos-cadera", video: "vK5p7UP9E2M", nombre: "Círculos de cadera", categoria: "calentamiento", segundos: 40,
    img: "assets/img/circulos-cadera.png", wger: 1862,
    claves: ["Manos en la cintura", "Círculos amplios y controlados", "20 s por sentido"] },

  // ── Grupo: piernas y glúteos ───────────────────────────────────────────
  { id: "sentadilla-lenta", video: "VRKdOsad3HQ", nombre: "Sentadilla lenta", categoria: "fuerza", grupo: "piernas", segundos: 45, repes: "×12",
    img: "assets/img/sentadilla-lenta.png", wger: 1963,
    claves: ["Pies al ancho de hombros", "Baja en 3 tiempos, sube en 2", "Talones siempre apoyados"] },
  { id: "zancadas-inversas", video: "wF96HPOuf7E", nombre: "Zancadas inversas", categoria: "fuerza", grupo: "piernas", segundos: 45, repes: "×8 por pierna",
    img: "assets/img/zancadas-inversas.png", wger: 999,
    claves: ["Paso atrás largo", "Rodilla de atrás baja sin tocar el suelo", "Torso erguido"] },
  { id: "puente-gluteos", video: "NUFvi-gPojg", nombre: "Puente de glúteos", categoria: "fuerza", grupo: "piernas", segundos: 45, repes: "×15",
    img: "assets/img/puente-gluteos.png", wger: 265,
    claves: ["Tumbado, pies cerca del glúteo", "Empuja con los talones", "Aprieta el glúteo 2 s arriba"] },
  { id: "elevacion-talones", video: "aAniiWqBuOY", nombre: "Elevación de talones", categoria: "fuerza", grupo: "piernas", segundos: 40, repes: "×15",
    img: "assets/img/elevacion-talones.png", wger: 1243,
    claves: ["Sube los talones despacio", "Baja controlando", "Apóyate en la pared si hace falta"] },
  { id: "wall-sit", video: "-qXuHrdmk4g", nombre: "Sentadilla isométrica en pared", categoria: "fuerza", grupo: "piernas", segundos: 40,
    img: "assets/img/video-wall-sit.jpg",
    claves: ["Espalda pegada a la pared", "Muslos paralelos al suelo", "Peso en los talones"] },
  { id: "step-ups", video: "vr2c1xKRmvU", nombre: "Step-ups en escalón", categoria: "fuerza", grupo: "piernas", segundos: 45, repes: "×10 por pierna",
    img: "assets/img/step-ups.png", wger: 981,
    claves: ["Sube al escalón con una pierna", "Impulsa con el talón", "Alterna o haz 20 s por lado"] },
  { id: "kneeling-kickbacks", video: "efdtizTcRT4", nombre: "Patada de glúteo a cuatro patas", categoria: "fuerza", grupo: "piernas", segundos: 40, repes: "×12 por pierna",
    img: "assets/img/kneeling-kickbacks.png", wger: 990,
    claves: ["A cuatro patas", "Estira una pierna hacia atrás", "Cadera cuadrada, sin arquear la lumbar"] },

  // ── Grupo: core ────────────────────────────────────────────────────────
  { id: "plancha-frontal", video: "kpZg8IIM-to", nombre: "Plancha frontal", categoria: "fuerza", grupo: "core", segundos: 40,
    img: "assets/img/plancha-frontal.png", wger: 1307,
    claves: ["Codos bajo los hombros", "Cuerpo en línea recta", "Abdomen y glúteo apretados"] },
  { id: "plancha-toques-hombro", video: "N-Jld43R5bw", nombre: "Plancha con toques de hombro", categoria: "fuerza", grupo: "core", segundos: 40, repes: "×16",
    img: "assets/img/plancha-toques-hombro.png", wger: 1091,
    notaHombro: "Si molesta el hombro, plancha de codos normal",
    claves: ["Plancha alta, pies anchos", "Toca el hombro contrario sin mover la cadera"] },
  { id: "plancha-lateral", video: "45t3tTcRcKE", nombre: "Plancha lateral", categoria: "fuerza", grupo: "core", segundos: 40,
    img: "assets/img/plancha-lateral.jpg",
    notaHombro: "Versión amable: apoya la rodilla; si nota pinchazo, plancha frontal",
    claves: ["Codo bajo el hombro", "Cadera arriba, cuerpo en línea", "20 s por lado"] },
  { id: "bird-dog", video: "YHehHSKJyHg", nombre: "Bird dog", categoria: "fuerza", grupo: "core", segundos: 40, repes: "×8 por lado",
    img: "assets/img/bird-dog.png", wger: 1572,
    claves: ["A cuatro patas", "Estira brazo y pierna contrarios", "Cadera estable, sin arquear la lumbar"] },
  { id: "dead-bug", video: "XkTtXA3-IqU", nombre: "Dead bug", categoria: "fuerza", grupo: "core", segundos: 40, repes: "×8 por lado",
    img: "assets/img/video-dead-bug.jpg",
    claves: ["Tumbado, brazos al cielo", "Baja brazo y pierna contrarios despacio", "Lumbar pegada al suelo"] },
  { id: "superman", video: "FWaMfMSJy3I", nombre: "Superman", categoria: "fuerza", grupo: "core", segundos: 40, repes: "×12",
    img: "assets/img/video-superman.jpg",
    claves: ["Boca abajo, brazos delante", "Eleva suave brazos y pecho", "Cuello neutro, mirada al suelo"] },
  { id: "crunch-lateral", video: "NGXahixAFyY", nombre: "Crunch lateral", categoria: "fuerza", grupo: "core", segundos: 40, repes: "×12 por lado",
    img: "assets/img/crunch-lateral.png", wger: 576,
    claves: ["Manos a los lados de la cabeza", "Lleva codo hacia rodilla contraria", "Sin tirar del cuello"] },
  { id: "crunch", video: "oRIi-jKzCro", nombre: "Crunch", categoria: "fuerza", grupo: "core", segundos: 40, repes: "×15",
    img: "assets/img/crunch.png", wger: 167,
    claves: ["Tumbado, rodillas flexionadas", "Sube hombros del suelo contrayendo el abdomen", "Sin tirar del cuello"] },
  { id: "elevacion-piernas-suelo", video: "eEbq5_AIgpo", nombre: "Elevación de piernas tumbado", categoria: "fuerza", grupo: "core", segundos: 40, repes: "×12",
    img: "assets/img/elevacion-piernas-suelo.png", wger: 377,
    claves: ["Tumbado, manos bajo el glúteo", "Sube las piernas rectas despacio", "Baja sin tocar el suelo"] },

  // ── Grupo: torso (empuje amable con el hombro) ─────────────────────────
  { id: "flexion", video: "b2UagYWNErY", nombre: "Flexiones (versión amable)", categoria: "fuerza", grupo: "torso", segundos: 45, repes: "×10",
    img: "assets/img/flexion.png", wger: 1551,
    notaHombro: "Manos en pared o banco si hace falta; codos cerca del cuerpo y baja solo hasta donde no duela",
    claves: ["Codos a 45°, no abiertos", "Cuerpo en línea", "Baja controlando"] },

  // ── Grupo: cardio de bajo impacto ──────────────────────────────────────
  { id: "mountain-climbers", video: "FPLXxBxYcmE", nombre: "Mountain climbers", categoria: "cardio", grupo: "cardio", segundos: 40,
    img: "assets/img/mountain-climbers.jpg",
    claves: ["Plancha alta", "Rodilla al pecho alternando", "Ritmo controlado, sin rebote"] },
  { id: "high-knees", video: "iBpgkuFuENY", nombre: "Rodillas altas en el sitio", categoria: "cardio", grupo: "cardio", segundos: 40,
    img: "assets/img/high-knees.png", wger: 983,
    claves: ["Sube las rodillas a la altura de la cadera", "Sin saltar si prefieres bajo impacto", "Los brazos acompañan el ritmo"] },

  // ── Estiramientos (vuelta a la calma) ──────────────────────────────────
  { id: "est-rodilla-al-pecho", video: "aUvk6eS_LDs", nombre: "Rodilla al pecho", categoria: "estiramiento", segundos: 50,
    img: "assets/img/est-rodilla-al-pecho.png", wger: 1452,
    claves: ["Tumbado, lleva una rodilla al pecho", "30 s por lado", "Respira profundo"] },
  { id: "est-cuadriceps", video: "vgpx6cOBXFM", nombre: "Estiramiento de cuádriceps", categoria: "estiramiento", segundos: 50,
    img: "assets/img/est-cuadriceps.png", wger: 1873,
    claves: ["De pie, talón hacia el glúteo", "Apóyate en la pared si hace falta", "30 s por lado"] },
  { id: "est-flexor-cadera", video: "8xZlzcMAtVQ", nombre: "Estiramiento de flexor de cadera", categoria: "estiramiento", segundos: 50,
    img: "assets/img/est-flexor-cadera.png", wger: 1867,
    claves: ["Rodilla atrás, empuja la cadera adelante", "Costillas abajo", "30 s por lado"] },
  { id: "est-paloma", video: "b_FPLGeUcSc", nombre: "Postura de la paloma", categoria: "estiramiento", segundos: 50,
    img: "assets/img/est-paloma.png", wger: 1872,
    claves: ["Tobillo delante, pierna de atrás estirada", "Baja el torso despacio", "30 s por lado"] },
  { id: "est-cuatro-figuras", video: "C12bTqPVGDs", nombre: "Cuatro figuras tumbado", categoria: "estiramiento", segundos: 50,
    img: "assets/img/est-cuatro-figuras.png", wger: 1869,
    claves: ["Tobillo sobre la rodilla contraria", "Tira del muslo hacia el pecho", "30 s por lado"] },
  { id: "est-lateral", video: "0Ri2ROhpNb8", nombre: "Estiramiento lateral de tronco", categoria: "estiramiento", segundos: 50,
    img: "assets/img/est-lateral.png", wger: 1861,
    claves: ["Brazo arriba, inclina a un lado", "Sin rotar el torso", "30 s por lado"] },
  { id: "est-postura-nino", video: "PC1IkjO1k5Q", nombre: "Postura del niño", categoria: "estiramiento", segundos: 50,
    img: "assets/img/childs-pose.png", wger: 1002,
    notaHombro: "Con los brazos a los lados del cuerpo para no cargar el hombro",
    claves: ["De rodillas, glúteos sobre talones", "Frente hacia el suelo", "Respira lento y profundo"] },
  { id: "est-gemelo", video: "fn1_NOnO1D0", nombre: "Estiramiento de gemelo", categoria: "estiramiento", segundos: 50,
    img: "assets/img/est-gemelo.png", wger: 1239,
    claves: ["Antepié en el borde de un escalón", "Baja el talón despacio", "Rodilla recta"] },
  { id: "est-isquiotibiales", video: "CLQUOJZlJNM", nombre: "Estiramiento de isquiotibiales", categoria: "estiramiento", segundos: 50,
    img: "assets/img/est-isquiotibiales.png", wger: 1870,
    claves: ["Tumbado, banda o toalla en el pie", "Sube la pierna recta", "30 s por lado"] },

  // ── Ampliación de biblioteca (2026-09-15) ──────────────────────────────
  { id: "head-turns", video: "qp5CHrB1cNY", nombre: "Giros de cabeza", categoria: "calentamiento", segundos: 30,
    img: "assets/img/head-turns.png",
    claves: ["Gira la cabeza despacio hacia los lados", "Sin forzar el rango", "Hombros relajados"] },
  { id: "tobillos", video: "ykS__niktzg", nombre: "Movilidad de tobillo", categoria: "calentamiento", segundos: 30,
    img: "assets/img/tobillos.png",
    claves: ["Flexiona y extiende el tobillo despacio", "Ritmo continuo", "20 s por pie"] },
  { id: "abrazo-rodilla", video: "ZDpA2BloL7s", nombre: "Abrazo de rodilla caminando", categoria: "calentamiento", segundos: 40,
    img: "assets/img/video-abrazo-rodilla.jpg",
    claves: ["Abraza una rodilla al pecho", "Alterna caminando", "Espalda recta"] },
  { id: "sentadilla-sumo", video: "ov0Vm_JFglo", nombre: "Sentadilla sumo", categoria: "fuerza", grupo: "piernas", segundos: 50, repes: "×12",
    img: "assets/img/video-sentadilla-sumo.jpg",
    claves: ["Pies anchos, puntas hacia fuera", "Rodillas abren siguiendo las puntas", "Pecho arriba"] },
  { id: "zancada-lateral", video: "6A7A8ua-sKQ", nombre: "Zancada lateral", categoria: "fuerza", grupo: "piernas", segundos: 45, repes: "×8 por lado",
    img: "assets/img/video-zancada-lateral.jpg",
    claves: ["Paso amplio a un lado", "Rodilla sigue la punta del pie", "Pierna contraria recta"] },
  { id: "puente-unapierna", video: "Mege8_sbT6M", nombre: "Puente de glúteos a una pierna", categoria: "fuerza", grupo: "piernas", segundos: 45, repes: "×8 por pierna",
    img: "assets/img/video-puente-unapierna.jpg",
    claves: ["Un tobillo cruza sobre la rodilla contraria", "Empuja con el talón de apoyo", "Cadera estable"] },
  { id: "sentadilla-bulgara", video: "klq4ahI59sY", nombre: "Sentadilla búlgara con silla", categoria: "fuerza", grupo: "piernas", segundos: 45, repes: "×8 por pierna",
    img: "assets/img/video-sentadilla-bulgara.jpg",
    nota: "Silla estable detrás: apoya el empeine",
    claves: ["Empeine de atrás sobre la silla", "Baja vertical, sin adelantar", "Torso erguido"] },
  { id: "abduccion-tumbado", video: "Q2Cokw_clyw", nombre: "Abducción de cadera tumbado", categoria: "fuerza", grupo: "piernas", segundos: 40, repes: "×15 por lado",
    img: "assets/img/video-abduccion-tumbado.jpg",
    claves: ["Tumbado de lado", "Sube la pierna recta", "Sin rotar la cadera"] },
  { id: "sentadilla-salto", video: "IiHH0EWo8-k", nombre: "Sentadilla con salto", categoria: "cardio", grupo: "cardio", segundos: 40, repes: "×10",
    img: "assets/img/video-sentadilla-salto.jpg",
    nota: "Sin salto si prefieres bajo impacto: sube a puntas de pies",
    claves: ["Baja a sentadilla", "Salta estirando el cuerpo", "Aterriza suave"] },
  { id: "tijeras", video: "V9V-XXHo294", nombre: "Tijeras abdominales", categoria: "fuerza", grupo: "core", segundos: 40, repes: "×20 alternando",
    img: "assets/img/video-tijeras.jpg",
    claves: ["Tumbado, piernas rectas y bajas", "Alterna arriba y abajo", "Lumbar pegada al suelo"] },
  { id: "tocar-puntas", video: "zHbxwCy1KTI", nombre: "Tocar puntas de los pies", categoria: "fuerza", grupo: "core", segundos: 40, repes: "×16",
    img: "assets/img/video-tocar-puntas.jpg",
    claves: ["Piernas verticales al cielo", "Toca las puntas con las manos", "Despega solo los hombros"] },
  { id: "esfinge", video: "by_gvo1FCdQ", nombre: "Postura de la esfinge", categoria: "estiramiento", segundos: 50,
    img: "assets/img/video-esfinge.jpg",
    claves: ["Boca abajo, antebrazos al suelo", "Pecho arriba sin molestar la lumbar", "Hombros lejos de las orejas"] },
  { id: "mariposa", video: "qrlkNhxDlBs", nombre: "Estiramiento de aductores (mariposa)", categoria: "estiramiento", segundos: 50,
    img: "assets/img/video-mariposa.jpg",
    claves: ["Sentado, plantas de los pies juntas", "Deja caer las rodillas", "Espalda larga"] },
  { id: "est-zancada-corredor", video: "2kfJTHITa4w", nombre: "Estiramiento de zancada del corredor", categoria: "estiramiento", segundos: 50,
    img: "assets/img/est-zancada-corredor.png",
    claves: ["Zancada amplia, rodilla de atrás estirada", "Empuja la cadera adelante", "30 s por lado"] },

  { id: "giros-brazos", video: "_zNxZGOjNXk", nombre: "Círculos de brazos", categoria: "calentamiento", segundos: 30,
    img: "assets/img/video-giros-brazos.jpg",
    claves: ["Círculos amplios con los brazos", "Delante y detrás", "Sin pasar de la horizontal si notas el hombro"] },
  { id: "rotacion-tronco", video: "7dlcn_yWqBU", nombre: "Rotación de tronco de pie", categoria: "calentamiento", segundos: 30,
    img: "assets/img/video-rotacion-tronco.jpg",
    claves: ["Gira el tronco a los lados", "Brazos sueltos acompañando", "Sin tirones"] },
  { id: "balanceo-piernas", video: "B8b_XlFeu3I", nombre: "Balanceo de piernas", categoria: "calentamiento", segundos: 30,
    img: "assets/img/video-balanceo-piernas.jpg",
    claves: ["Apóyate en la pared", "Balancea una pierna adelante y atrás", "20 s por pierna"] },
  { id: "flexion-inclinada", video: "uCTbmCjiF7Y", nombre: "Flexiones inclinadas en pared", categoria: "fuerza", grupo: "torso", segundos: 40, repes: "×10",
    img: "assets/img/video-flexion-inclinada.jpg",
    notaHombro: "Cuanto más vertical la pared, menos carga en el hombro",
    claves: ["Manos a la altura del pecho", "Codos a 45°", "Cuerpo en línea"] },
  { id: "skater", video: "Xz27DudBfSs", nombre: "Salto de patinador lateral", categoria: "cardio", grupo: "cardio", segundos: 40, repes: "×16 alternando",
    img: "assets/img/video-skater.jpg",
    nota: "Sin saltar si prefieres bajo impacto: paso lateral amplio",
    claves: ["Salta de un pie al otro lateralmente", "Rodilla suave al aterrizar", "Brazos equilibran"] },

];

const CATEGORIAS = {
  calentamiento: { nombre: "Calentamiento", emoji: "🔥" },
  fuerza: { nombre: "Fuerza", emoji: "💪" },
  cardio: { nombre: "Cardio", emoji: "⚡" },
  estiramiento: { nombre: "Estiramiento", emoji: "🧘" },
};

const GRUPOS = {
  piernas: "Piernas y glúteos",
  core: "Core",
  torso: "Torso (empuje amable)",
  cardio: "Cardio",
};
